CREATE TABLE public.albums (
	album_id int4 NULL,
	title varchar(1024) NULL,
	artist_name varchar(1024) NULL,
	artist_id int4 NULL,
	discogs_id int4 NULL,
	barcode varchar(1024) NULL,
	genres varchar NULL,
	country varchar NULL,
	image_url varchar NULL,
	"year" int4 NULL
);

INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(1, 'Long Live A.S.A.P.', 'A.S.A.P. Rocky', 1, NULL, '887654369611', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(2, 'Moon Safari', 'Air', 2, NULL, '17046664417', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(3, 'Alt-J', 'Alt-J (∆)', 3, NULL, '75678762819', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(4, 'American Football', 'American Football', 4, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(5, 'Mysterious Production of Eggs', 'Andrew Bird', 5, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(6, 'Merriweather Post Pavilion', 'Animal Collective', 6, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(7, 'Sung Tongs', 'Animal Collective', 6, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(8, 'Reflektor', 'Arcade Fire', 7, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(9, 'Logos', 'Atlas Sound', 8, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(10, 'Cease to Begin', 'Band Of Horses', 9, NULL, '98787074512', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(11, 'Devotion', 'Beach House', 10, NULL, '677517004212', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(12, 'Beyonce', 'Beyonce', 11, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(13, '1942-1952-1954', 'Billy Holiday', 12, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(14, 'Greatest Hits', 'Bob Dylan', 13, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(15, 'Exodus', 'Bob Marley & The Wailers', 14, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(16, 'Blood Bank', 'Bon Iver', 15, NULL, '656605213415', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(17, 'For Emma, Forever Ago', 'Bon Iver', 15, NULL, '656605211510', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(18, 'Broken Social Scene', 'Broken Social Scene', 16, NULL, '827590140011', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(19, 'You Forgot it in People', 'Broken Social Scene', 16, NULL, '827590010017', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(20, 'Untitled', 'Charles Manson', 17, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(21, 'Rush of Blood to the Head', 'Coldplay', 18, NULL, '724354050411', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(22, 'Untitled', 'Cole Alexander & Bradford Cox', 19, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(23, 'Ressurection', 'Common', 20, NULL, '88561120818', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(24, 'So Far', 'Crosby, Stills, Nash, and Young', 21, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(25, 'Silent Hour/Gold Mile', 'Daniel Rossen', 22, NULL, '801061933210', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(26, 'XXX', 'Danny Brown', 23, NULL, '856730003169', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(27, 'Tonight', 'David Bowie', 24, NULL, '77771713811', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(28, 'For The Whole World To See', 'Death', 25, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(29, 'Transatlanticsm', 'Death Cab For Cutie', 26, NULL, '655173103210', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(30, 'Microcastle/Weird Era Continues', 'Deerhunter', 27, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(31, 'Cripple Crow', 'Devendra Bandhart', 28, NULL, '634904019211', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(32, 'Nothing Was the Same (Deluxe)', 'Drake', 29, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(33, 'What A Time To Be Alive', 'Drake & Future', 30, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(34, 'Daybreak Express', 'Duke Ellington', 31, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(35, 'I Will Be', 'Dum Dum Girls', 32, NULL, '98787084016', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(36, 'Easy Star''s Lonely Hearts Dub Band', 'Easy Star All Stars', 33, NULL, '657481101810', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(37, 'Elliot Smith', 'Elliot Smith', 34, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(38, 'Greatest Hits', 'Elton John', 35, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(39, 'Greatest Hits Vol. 2', 'Elton John', 35, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(40, 'Elvis'' Golden Record', 'Elvis Presley', 36, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(41, 'Fleet Foxes', 'Fleet Foxes', 37, NULL, '98787077711', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(42, 'Helplessness Blues', 'Fleet Foxes', 37, NULL, '98787088816', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(43, 'Rumors', 'Fleetwood Mac', 38, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(44, 'We Are The 21st Century Ambassadors of Peace and Magic', 'Foxygen', 39, NULL, '656605222714', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(45, 'channel orange', 'Frank Ocean', 40, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(46, 'Album', 'Girls', 41, NULL, '744861601012', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(47, 'Cruel Summer', 'GOOD Music', 42, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(48, 'Shields', 'Grizzly Bear', 43, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(49, 'Veckatimest', 'Grizzly Bear', 43, NULL, '801061018214', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(50, 'Yellow House', 'Grizzly Bear', 43, NULL, '801061714710', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(51, 'Love, Angel, Music, Baby', 'Gwen Stafani', 44, NULL, '75021031432', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(52, 'Days Are Gone', 'Haim', 45, NULL, '888837709712', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(53, 'Grace', 'Jeff Buckley', 46, NULL, '886977798313', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(54, 'Axis Bold as Love', 'Jimi Hendrix', 47, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(55, 'Experience: Smash Hits', 'Jimi Hendrix', 47, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(56, 'Imagine', 'John Lennon', 48, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(57, 'Plastic Ono Band', 'John Lennon', 48, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(58, 'I Walk The Line', 'Johnny Cash', 49, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(59, '808s and Heartbreak', 'Kanye West', 50, NULL, '602517872813', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(60, 'College Dropout', 'Kanye West', 50, NULL, '602498617410', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(61, 'Late Registration', 'Kanye West', 50, NULL, '602498824047', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(62, 'My Beautiful Dark Twisted Fantasy', 'Kanye West', 50, NULL, '602527594934', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(63, 'Yeezus', 'Kanye West', 50, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(64, 'Graduation', 'Kanye West', 50, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(65, 'Watch The Throne', 'Kanye West & Jay Z', 51, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(66, 'Good, M.A.A.D City', 'Kendrick Lamar', 52, NULL, '602537192267', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(67, 'To Pimp a Butterfly', 'Kendrick Lamar', 52, NULL, '602547311009', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(68, 'Section 80', 'Kendrick Lamar', 52, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(69, 'Smoke Ring For My Halo', 'Kurt Vile', 53, NULL, '744861093817', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(70, 'I', 'Led Zeppelin', 54, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(71, 'In Through The Out Door', 'Led Zeppelin', 54, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(72, 'IV', 'Led Zeppelin', 54, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(73, 'Physical Graffiti', 'Led Zeppelin', 54, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(74, 'Machine Dreams', 'Little Dragon', 55, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(75, 'Little Joy', 'Little Joy', 56, NULL, '883870048514', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(76, 'Gorrila Manor', 'Local Natives', 57, NULL, '675640913517', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(77, 'Hummingbird', 'Local Natives', 57, NULL, '675640915511', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(78, 'Walk on the Wild Side, Best of Lou Reed', 'Lou Reed', 58, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(79, 'Salad Days', 'Mac DeMarco', 59, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(80, '16 of their greatest hits', 'Mamas and the Papas', 60, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(81, 'Greatest Hits', 'Marvin Gaye', 61, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(82, 'Kala', 'M.I.A.', 62, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(83, 'Thriller', 'Michael Jackson', 63, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(84, 'Davis', 'Miles Davis', 64, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(85, 'Sigh No More', 'Mumford & Sons', 65, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(86, 'Decade', 'Neil Young', 66, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(87, 'Stankonia', 'Outkast', 67, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(88, 'Aquemini', 'Outkast', 67, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(89, 'Person Pitch', 'Panda Bear', 68, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(90, 'Tomboy', 'Panda Bear', 68, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(91, 'Band on the Run', 'Paul McCartney & Wings', 69, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(92, 'Hearts and Bones', 'Paul Simon', 70, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(93, 'Animals', 'Pink Floyd', 71, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(94, 'Dark Side of the Moon', 'Pink Floyd', 71, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(95, 'Meddle', 'Pink Floyd', 71, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(96, 'Wish You Were Here', 'Pink Floyd', 71, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(97, 'Third', 'Portishead', 72, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(98, 'Greatest Hits', 'Queen', 73, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(99, 'Amnesiac', 'Radiohead', 74, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(100, 'Hail to the Theif', 'Radiohead', 74, NULL, '724358454314', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(101, 'In Rainbows', 'Radiohead', 74, NULL, '880882162313', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(102, 'Kid-A', 'Radiohead', 74, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(103, 'King of Limbs', 'Radiohead', 74, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(104, 'OK Computer', 'Radiohead', 74, NULL, '724385522918', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(105, 'Raising Sand', 'Robert Plant & Allison Krause ', 75, NULL, '11661907515', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(106, 'Greatest Hits', 'Santana', 76, NULL, '74643305013', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(107, 'Black Up', 'Shabbaz Palaces', 77, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(108, 'Greatest Hits', 'Simon & Garfunkel', 78, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(109, 'Stan Getz with Guests artist Laurindo Almeda', 'Stan Getz', 79, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(110, 'Inspiration Information', 'Shuggie Otis', 80, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(111, 'Interspeaker', 'Tame Impala', 81, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(112, 'Currents', 'Tame Impala', 81, NULL, '602547306777', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(113, '1962-1966', 'The Beatles', 82, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(114, '1967-1970', 'The Beatles', 82, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(115, 'Abbey Road', 'The Beatles', 82, NULL, '77774644617', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(116, 'Help!', 'The Beatles', 82, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(117, 'Magical Mystery Tour', 'The Beatles', 82, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(118, 'Revolver', 'The Beatles', 82, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(119, 'Rubber Soul', 'The Beatles', 82, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(120, 'Sgt Pepper''s Lonely Hearts Club Band', 'The Beatles', 82, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(121, 'The Second Album', 'The Beatles', 82, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(122, 'White Album', 'The Beatles', 82, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(123, 'Let it Be', 'The Beatles ', 82, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(124, 'Greatest Hits', 'The Byrds', 84, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(125, 'Best Of', 'The Doors', 85, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(126, 'Yoshimi Battles The Pink Robots', 'The Flaming Lips', 86, NULL, '93624814115', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(127, 'The Soft Bulletin', 'The Flaming Lips', 86, NULL, '93624952183', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(128, 'State of Confusion', 'The Kinks', 87, NULL, '78221801812', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(129, 'Exhile on Main Street', 'The Rolling Stones', 88, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(130, 'Hot Rocks 1964-1971', 'The Rolling Stones', 88, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(131, 'Tattoo You', 'The Rolling Stones', 88, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(132, 'Wincing The Night Away', 'The Shins', 89, NULL, '98787070514', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(133, 'Is This it?', 'The Strokes', 90, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(134, '25th Anniversary', 'The Temptations', 91, NULL, '50109538911', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(135, 'Lost in the Dream', 'The War on Drugs', 92, NULL, '656605031019', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(136, 'House of Balloons', 'The Weeknd', 93, NULL, '602547264756', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(137, 'The White Stripes', 'The White Stripes', 94, NULL, '634904014919', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(138, 'The Best of', 'The Zombies', 95, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(139, 'Vibes', 'Theophilus London', 96, NULL, '93624934653', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(140, 'The Eraser', 'Tom Yorke', 97, NULL, '634904020019', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(141, 'Rodeo', 'Travis Scott', 98, NULL, '888750652010', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(142, 'II', 'Unknown Mortal Orchestra', 99, NULL, '656605223216', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(143, 'Multilove', 'Unknown Mortal Orchestra', 99, NULL, '656605226217', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(144, 'Unknown Mortal Orchestra', 'Unknown Mortal Orchestra', 99, NULL, '767981125015', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(145, 'Andy Warhol', 'Velvet Underground', 100, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(146, 'Velvet Underground', 'Velvet Underground', 100, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(147, 'Summertime 06', 'Vince Staples', 101, NULL, '602547552167', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(148, 'Everything Goes Wrong', 'Vivian Girls', 102, NULL, '759718517910', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(149, 'What For?', 'Toro Y Moi', 103, NULL, '677517010213', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(150, 'Life of Pablo', 'Kanye West', 50, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(151, 'Blonde', 'Frank Ocean', 40, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(152, 'Lemonade', 'Beyonce', 11, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(153, 'The Score', 'The Fugees', 104, NULL, '887654009111', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(154, 'Seat at the Table', 'Solange', 105, NULL, '889853874712', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(155, 'Game Theory', 'The Roots', 106, NULL, '602517040953', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(156, 'Discover', 'Daft Punk', 107, NULL, '724384960612', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(157, 'Milosc Jest Cudowna', 'Maanam', 108, 7813374, '825646018680', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(158, 'Oxnard', 'Anderson .Paak', 109, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(159, 'Jesus Is King', 'Kanye West', 50, 15163360, '602508464669', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(160, 'Mordechai', 'Khruangbin', 110, NULL, '656605149318', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(161, 'Days Before Rodeo', 'Travis Scott', 98, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(162, 'Spice World', 'Spice Girls', 111, NULL, '602508119378', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(163, 'Beyonce', 'Beyonce', 11, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(164, 'The Eagles', 'The Eagles', 112, NULL, '81227961671', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(165, 'Spice Girls', 'Spice Girls', 111, NULL, '17046754415', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(166, 'Old King Cole Younger', 'Various Artists', 113, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(167, 'Innerspeaker', 'Tame Impala', 81, NULL, '879198005728', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(168, 'Malibu', 'Anderson .Paak', 109, NULL, '885150342237', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(169, 'Metaphorical Music', 'Nujabes', 114, 12639854, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(170, 'Random Access Memories', 'Daft Punk', 107, NULL, '888837168618', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(171, 'Black Pumas', 'Black Pumas', 115, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(172, 'Try!', 'John Mayer Trio', 116, NULL, '827969511510', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(173, 'Nostalgia Ultra', 'Frank Ocean', 40, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(174, 'Invasion Of Privacy', 'Cardi B', 117, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(175, 'Awaken My Love', 'Childish Gambino', 118, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(176, 'Circles', 'Mac Miller', 119, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(177, 'Damn', 'Kendrick Lamar', 52, 10448824, '602557618280', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(178, 'Writings On The Wall', 'Destiny''s Child', 120, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(179, 'thank u, next', 'Ariana Grande', 121, NULL, '602577476228', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(180, 'Devine Feminine', 'Mac Miller', 119, NULL, '93624916031', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(181, 'Scumfuck Flowerboy', 'Tyler, The Creator', 122, NULL, '889854690519', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(182, 'The Worst of Jefferson Airplane', 'Jefferson Airplane', 123, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(183, 'Hive Mind', 'The Internet', 124, 12269361, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(184, 'Roam', 'Audiences', 125, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(185, 'Kids See Ghosts', 'Kids See Ghosts', 126, NULL, '602567800484', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(186, 'Sweetener', 'Ariana Grande', 121, NULL, '602577005954', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(187, 'Igor', 'Tyler, The Creator', 122, NULL, '190759652312', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(188, 'Sex & Food', 'Unknown Mortal Orchestra', 99, NULL, '656605232218', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(189, 'Repetitions (Letters to Krzysztof Komeda)', 'EABS', 127, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(190, 'American Dreams', 'Luke Henry', 128, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(191, 'Funk Wav Bounces Vol. 1', 'Calvin Harris', 129, NULL, '889854434212', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(192, 'Apollo 21', 'Steve Lacy', 130, NULL, '5056167113843', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(193, 'Negro Swan', 'Blood Orange', 131, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(194, 'Tomorrow', 'The O''Mys', 132, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(195, 'Third Eye Blind', 'Third Eye Blind', 133, NULL, '8718469536627', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(196, 'IV', 'BADBADNOTGOOD', 134, NULL, '810874021526', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(197, 'Madvilliany', 'Madvillian', 135, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(198, 'Swimming', 'Mac Miller', 119, NULL, '', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(199, 'III', 'BADBADNOTGOOD', 134, NULL, '810874020505', NULL, NULL, NULL, NULL);
INSERT INTO public.albums (album_id, title, artist_name, artist_id, discogs_id, barcode, genres, country, image_url, "year") VALUES(200, '17 Songs for Christmas', 'Franciscan Cleric Choir', 136, NULL, '', NULL, NULL, NULL, NULL);


	 CREATE TABLE public.artists(
	    artist_id         INTEGER  NOT NULL PRIMARY KEY
	   ,name       VARCHAR(31) NOT NULL
	   ,discogs_id VARCHAR(30)
	   ,photo_url  VARCHAR(30)
	 );

	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (1,'A.S.A.P. Rocky',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (2,'Air',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (3,'Alt-J (∆)',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (4,'American Football',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (5,'Andrew Bird',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (6,'Animal Collective',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (7,'Arcade Fire',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (8,'Atlas Sound',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (9,'Band Of Horses',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (10,'Beach House',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (11,'Beyonce',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (12,'Billy Holiday',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (13,'Bob Dylan',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (14,'Bob Marley & The Wailers',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (15,'Bon Iver',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (16,'Broken Social Scene',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (17,'Charles Manson',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (18,'Coldplay',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (19,'Cole Alexander & Bradford Cox',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (20,'Common',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (21,'Crosby, Stills, Nash, and Young',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (22,'Daniel Rossen',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (23,'Danny Brown',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (24,'David Bowie',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (25,'Death',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (26,'Death Cab For Cutie',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (27,'Deerhunter',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (28,'Devendra Bandhart',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (29,'Drake',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (30,'Drake & Future',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (31,'Duke Ellington',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (32,'Dum Dum Girls',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (33,'Easy Star All Stars',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (34,'Elliot Smith',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (35,'Elton John',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (36,'Elvis Presley',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (37,'Fleet Foxes',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (38,'Fleetwood Mac',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (39,'Foxygen',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (40,'Frank Ocean',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (41,'Girls',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (42,'GOOD Music',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (43,'Grizzly Bear',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (44,'Gwen Stafani',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (45,'Haim',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (46,'Jeff Buckley',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (47,'Jimi Hendrix',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (48,'John Lennon',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (49,'Johnny Cash',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (50,'Kanye West',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (51,'Kanye West & Jay Z',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (52,'Kendrick Lamar',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (53,'Kurt Vile',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (54,'Led Zeppelin',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (55,'Little Dragon',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (56,'Little Joy',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (57,'Local Natives',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (58,'Lou Reed',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (59,'Mac DeMarco',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (60,'Mamas and the Papas',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (61,'Marvin Gaye',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (62,'M.I.A.',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (63,'Michael Jackson',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (64,'Miles Davis',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (65,'Mumford & Sons',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (66,'Neil Young',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (67,'Outkast',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (68,'Panda Bear',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (69,'Paul McCartney & Wings',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (70,'Paul Simon',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (71,'Pink Floyd',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (72,'Portishead',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (73,'Queen',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (74,'Radiohead',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (75,'Robert Plant & Allison Krause',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (76,'Santana',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (77,'Shabbaz Palaces',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (78,'Simon & Garfunkel',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (79,'Stan Getz',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (80,'Shuggie Otis',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (81,'Tame Impala',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (82,'The Beatles',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (84,'The Byrds',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (85,'The Doors',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (86,'The Flaming Lips',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (87,'The Kinks',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (88,'The Rolling Stones',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (89,'The Shins',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (90,'The Strokes',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (91,'The Temptations',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (92,'The War on Drugs',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (93,'The Weeknd',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (94,'The White Stripes',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (95,'The Zombies',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (96,'Theophilus London',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (97,'Tom Yorke',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (98,'Travis Scott',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (99,'Unknown Mortal Orchestra',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (100,'Velvet Underground',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (101,'Vince Staples',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (102,'Vivian Girls',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (103,'Toro Y Moi',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (104,'The Fugees',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (105,'Solange',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (106,'The Roots',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (107,'Daft Punk',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (108,'Maanam',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (109,'Anderson .Paak',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (110,'Khruangbin',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (111,'Spice Girls',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (112,'The Eagles',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (113,'Various Artists',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (114,'Nujabes',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (115,'Black Pumas',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (116,'John Mayer Trio',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (117,'Cardi B',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (118,'Childish Gambino',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (119,'Mac Miller',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (120,'Destiny''s Child',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (121,'Ariana Grande',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (122,'Tyler, The Creator',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (123,'Jefferson Airplane',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (124,'The Internet',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (125,'Audiences',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (126,'Kids See Ghosts',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (127,'EABS',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (128,'Luke Henry',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (129,'Calvin Harris',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (130,'Steve Lacy',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (131,'Blood Orange',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (132,'The O''Mys',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (133,'Third Eye Blind',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (134,'BADBADNOTGOOD',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (135,'Madvillian',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (136,'Franciscan Cleric Choir',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (137,'Thundercat',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (138,'Gorillaz',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (139,'Lauryn Hill',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (140,'Leon Bridges',NULL,NULL);
	 INSERT INTO public.artists(artist_id,name,discogs_id,photo_url) VALUES (141,'Red Hot Chili Peppers',NULL,NULL);
